name: Store Main Coverage
on: [push]
jobs:
  rspec:
    name: Rspec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
      - name: output
        run: cat coverage/.last_run.json
      - name: Parse JSON
        id: coverage-percentage
        shell: bash
        run: |
          value=`jq .result.covered_percent coverage/.last_run.json`
          echo "::set-output name=coverage::$value"
          echo $value
      - name: Show coverage
        run: echo "coverage is ${{ steps.coverage-percentage.outputs.coverage }}"
